# Лабораторна Работа №2

### Автор
- Гадиев Альберт AIN-2-22

In [9]:
import numpy as numpy
a = numpy.array([1,5,8])
a


array([1, 5, 8])

In [10]:
b = numpy.array([[4.5,5.6], [0.3, 2.4]])
b

array([[4.5, 5.6],
       [0.3, 2.4]])

In [11]:
c = numpy.array([[1,3,5],[5,7,0],[4,0,5]])
c

array([[1, 3, 5],
       [5, 7, 0],
       [4, 0, 5]])